### ISSUE TITLE
protobuild command not found

### ISSUE THREAD

**Issue by wangxf1987** [stevvooe/protobuild#13]
Hi, stevvooe
     I run follow steps,
     1) make setup -> normal, and all package instlled.
     2) make generate -> /bin/sh: protobuild command not found.
The protobuild has already installed under /root/go/src/github.com/stevvooe.

my go env like this, i run commands on the CentOS7.3
====================================
[root@host-172-19-146-103 github.com]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"

Any mistake ? thanks

**Comment by wangxf1987** [comment]
shoud i run make on the ubuntu?

**Comment by wangxf1987** [comment]
The issue have been resolevd, I use the branch bump_v17.06.5 in the swarmkit project, and make generate pass.
But if use the master, make generate failure. I think this is a bug.

**Comment by wangxf1987** [comment]
BTW, It's still run the command on the centos7.3.

**Comment by stevvooe** [comment]
You need to run `go get -u github.com/stevvooe/protobuild` to install it.

In the future, please file bugs with build problems with the actual project (in this case, swarmkit). Thanks!
