### ISSUE TITLE
Can not find golang package when executing the make command

### ISSUE THREAD

**Issue by wangxf1987** [stevvooe/protobuild#14]
Can not find golang package when executing the make command, and reprodution step is:
1. make setup -> pass
2. make -> command not found(lost package)
🐳 lint
/bin/sh: 1: golint: not found
🐳 ineffassign
/bin/sh: 1: ineffassign: not found
🐳 misspell
xargs: misspell: No such file or directory

**Comment by stevvooe** [comment]
What project are you trying to build? It looks like you are missing the metalinter tools (https://github.com/alecthomas/gometalinter). I would recommend filing a bug with swarmkit for help in the future.
