### ISSUE TITLE
What is logic behind write .pb.go files to GOPATH?

### ISSUE THREAD

**Issue by nizsheanez** [stevvooe/protobuild#19]
Good day. 
I have confused why outputDir is not configurable and why it pointing to GOPATH by default? 
```
outputDir := filepath.Join(gopathCurrent, "src")
```

Is there special reason which i missing? 

I tried to force GOPATH to directory where i would like to see .pb.go files, but got empty error:
```
GOPATH=./:$GOPATH protobuild . 
exit status 2


GOPATH=$(pwd):$GOPATH protobuild .                                                                                           
exit status 1
```
I think it's because of bug in `quiet` flag check:
```
if quiet {
	log.Println(arg)
}
```
Must be !quiet

**Comment by stevvooe** [comment]
Your Go project, where you are generating protobufs, is the top-level of the GOPATH, so that is where they land. If you are trying to build outside of GOPATH, this tool isn't really built for that.

**Comment by stevvooe** [comment]
To clarify, I might be generating for `github.com/stevvooe/mypkg/proto`, so that is where you put the generated protobufs. Where else would they go?

**Comment by nizsheanez** [comment]
With go1.11 modules - possible to work with GO without GOPATH at all. So, I feel that make it configurable - make sense. 

Also possible to have Multiple GOPATH and `gopathCurrent` is not really current - it's first.

**Comment by stevvooe** [comment]
@nizsheanez I am not sure how this project will work with modules, as I don't know how they are handling this use case. If you want to propose a design, please feel free, but right now, this project generates the output in GOPATH (and really whereever your project sits within it).

> Also possible to have Multiple GOPATH and gopathCurrent is not really current - it's first.

The code that calculates `gopathCurrent` chooses the first GOPATH, which is the working GOPATH.

If you want to use this project, you really need to follow https://golang.org/doc/code.html. I may support other workflows in the future but I don't want to make large changes until the module behavior has been worked out.

**Comment by nizsheanez** [comment]
Ok. No problem. Thank.

**Comment by stevvooe** [comment]
Closing this issue for now. I'll open an issue to add support for Go modules.
